### PR TITLE
Adding SDWIS widget

### PR DESCRIPTION
**Pull request by tbock**
@GeoFe33 putting some feedback here
- [x] all links should open in a new one on a href tags add target="_blank"  (mailto links appear to not have this but check them all)
- [x] Not Reported emails or any other links should not be clickable if no content
image
- [x] Not seeing any highlight of features to indicate selected. Is this b/c of the correct layer isn't in the map or is this not happening yet?  - working on this

### CODE REVIEW

**Comment by GeoFe33** [comment]
Comments added above.

**Comment by tbock** [comment]
None of the other widgets really zoom to the selected feature... don't think its needed here... Just the highlight should be good.

**Comment by GeoFe33** [comment]
Completed #2 & #3.  Highlight function is working.

**Comment by GeoFe33** [comment]
This is ready to be re-merged into the master.

**Pull request merged**
